### ISSUE TITLE
譜面分岐を行う小節線の手前の音符がほぼ二重になる。

### ISSUE THREAD

**Issue by romyu** [kairera0467/TJAP2fPC#62]
(ほぼ二重になる、というのは、たまに発生しないことがあるからです)
↓検証した譜面
https://ux.getuploader.com/Romyu_uploader_01/download/6

**Comment by kairera0467** [comment]
取り急ぎ3回ほどプレイしましたが再現できませんでした。
発生するバージョン(タイトル画面左上)と、検証した譜面で実際に発生した箇所を教えていただければ有り難いです。
じっくりプレイして試せるのはおそらく来週の金曜日以降かも...

**Comment by kairera0467** [comment]
ろみゅ～？さん曰く、「listChipとlistBranchの発声時刻msにずれがある」とのこと。
なお、2つの時間差はOFFSETの値と完全に一致している。

**Comment by kairera0467** [comment]
rev:0b5dff6dd7f34e914d6c747ebe1dd8357a6d933e で修正、このバグ修正を組み込んだVer2020032000をリリースしました。
私の環境で再現できなかったのは、この不具合がどうやら「WASAPI/ASIOでしか発生しなかったから」らしいです。
